services:
  todo_list_be:
    container_name: todo_list_be
    build: .
    ports:
      - ${EXPOSE_PORT}:${PORT}
    restart: always
    volumes:
      - ./:/app/
    depends_on:
      - todo_list_db
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${DB_HOST}:${DB_PORT}
      - WAIT_HOSTS=${DB_HOST}:${DB_PORT}

    networks:
      - todo-list-stack

  todo_list_db:
    image: postgres:15.2-alpine
    container_name: todo_list_db
    ports:
      - ${EXPOSE_DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    networks:
      - todo-list-stack

volumes:
  db:
    driver: local

networks:
  todo-list-stack:
    driver: bridge